<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Moon_WiiVC_Injector</RootNamespace>
    <AssemblyName>Moon WiiVC Injector</AssemblyName>
    <ApplicationIcon>WiiU.ico</ApplicationIcon>
    <NoWin32Manifest>true</NoWin32Manifest>
    <Description>Wii &amp; GameCube Virtual Console Injector for Wii U</Description>
    <RepositoryUrl>https://github.com/Rodrigo-Matsuura/TeconmoonWiiVCInjector</RepositoryUrl>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.11" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NKit\NKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\TOOLDIR.zip">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
    <EmbeddedResource Include="Resources\wiitdb.txt" />
    <EmbeddedResource Include="Resources\Base\**\*" />
    <EmbeddedResource Include="Resources\Dol\**\*" />
  </ItemGroup>
</Project>
